<a href="https://colab.research.google.com/github/RiShiKaRoRa22/AI_LAB/blob/main/assignment5connect4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a= int(input("enter prn :"))
b=a%4
print(b)

if(b==1):
  print("tictactoe")
elif(b==2):
  print("nim game2")
elif(b==3):
  print("connect 4")
else:
  print("gomuko")

enter prn :23070122178
2
nim game2


In [ ]:
import numpy as np
import math
import random

ROWS = 6
COLS = 7

PLAYER = 1
AI = 2
EMPTY = 0

DEPTH = 4

In [ ]:
def create_board():
    return np.zeros((ROWS, COLS))

def print_board(board):
    print(np.flip(board, 0))

def is_valid(board, col):
    return board[ROWS - 1][col] == 0

def get_row(board, col):
    for r in range(ROWS):
        if board[r][col] == 0:
            return r

def drop(board, row, col, piece):
    board[row][col] = piece

In [ ]:
def win(board, piece):
    for r in range(ROWS):
        for c in range(COLS - 3):
            if board[r][c:c+4].tolist().count(piece) == 4:
                return True

    for c in range(COLS):
        for r in range(ROWS - 3):
            if list(board[r:r+4, c]).count(piece) == 4:
                return True
    # Diag right to left
    for r in range(ROWS - 3):
        for c in range(COLS - 3):
            if [board[r+i][c+i] for i in range(4)].count(piece) == 4:
                return True
    # diag left to right
    for r in range(3, ROWS):
        for c in range(COLS - 3):
            if [board[r-i][c+i] for i in range(4)].count(piece) == 4:
                return True

    return False

In [ ]:
def evaluate(window, piece):
    score = 0
    opponent = PLAYER if piece == AI else AI

    if window.count(piece) == 4:
        score += 100
    elif window.count(piece) == 3 and window.count(EMPTY) == 1:
        score += 5
    elif window.count(piece) == 2 and window.count(EMPTY) == 2:
        score += 2

    if window.count(opponent) == 3 and window.count(EMPTY) == 1:
        score -= 4

    return score

In [ ]:
def score_board(board, piece):
    score = 0

    # Center preference
    center = list(board[:, COLS // 2])
    score += center.count(piece) * 3

    # Horizontal
    for r in range(ROWS):
        row = list(board[r, :])
        for c in range(COLS - 3):
            score += evaluate(row[c:c+4], piece)

    # Vertical
    for c in range(COLS):
        col = list(board[:, c])
        for r in range(ROWS - 3):
            score += evaluate(col[r:r+4], piece)

    return score

In [ ]:
def valid_moves(board):
    return [c for c in range(COLS) if is_valid(board, c)]

In [ ]:
def minimax(board, depth, maximizing):

    moves = valid_moves(board)
    terminal = win(board, PLAYER) or win(board, AI) or len(moves) == 0

    if depth == 0 or terminal:
        if win(board, AI):
            return None, 100000
        elif win(board, PLAYER):
            return None, -100000
        else:
            return None, score_board(board, AI)

    if maximizing:  # AI turn ai maximizes the min score by player
        best_score = -math.inf
        best_col = random.choice(moves)

        for col in moves:
            row = get_row(board, col)
            temp = board.copy()
            drop(temp, row, col, AI)

            _, score = minimax(temp, depth - 1, False)

            if score > best_score:
                best_score = score
                best_col = col

        return best_col, best_score

    else:  # Player turn- minimising the score

        best_score = math.inf
        best_col = random.choice(moves)

        for col in moves:
            row = get_row(board, col)
            temp = board.copy()
            drop(temp, row, col, PLAYER)

            _, score = minimax(temp, depth - 1, True)

            if score < best_score:
                best_score = score
                best_col = col

        return best_col, best_score

In [ ]:
board = create_board()
print_board(board)
turn = 0
game_over = False
while not game_over:
    if turn == 0:
        col = int(input("Your move (0-6): "))
        if is_valid(board, col):
            row = get_row(board, col)
            drop(board, row, col, PLAYER)
            if win(board, PLAYER):
                print("You Win!")
                game_over = True
    else:
        col, _ = minimax(board, DEPTH, True)
        row = get_row(board, col)
        drop(board, row, col, AI)
        print("AI plays:", col)

        if win(board, AI):
            print("AI Wins!")
            game_over = True

    print_board(board)
    turn = (turn + 1) % 2

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Your move (0-6): 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
AI plays: 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
Your move (0-6): 4
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0.]]
AI plays: 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 2. 1. 1. 0. 0.]]
Your move (0-6): 5
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 2. 1. 1. 1. 0.]]
AI plays: 6
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0.